In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [2]:
df3 = pd.read_csv("customers.csv")

In [3]:
df3.head()

,customer_id,first_name,last_name,phone,email,street,city,state,zip_code
0,1,Debra,Burks,NaN,debra.burks@yahoo.com,9273 Thorne Ave.,Orchard Park,NY,14127
1,2,Kasha,Todd,NaN,kasha.todd@yahoo.com,910 Vine Street,Campbell,CA,95008
2,3,Tameka,Fisher,NaN,tameka.fisher@aol.com,769C Honey Creek St.,Redondo Beach,CA,90278
3,4,Daryl,Spence,NaN,daryl.spence@aol.com,988 Pearl Lane,Uniondale,NY,11553
4,5,Charolette,Rice,(916) 381-6003,charolette.rice@msn.com,107 River Dr.,Sacramento,CA,95820

In [4]:
columns_df3 = df3.columns.tolist()
# Remove customer_name from its current position
columns_df3.remove('customer_name')
# Find the index of 'customer_id'
customer_id_index = columns_df3.index('customer_id')
# Insert 'customer_name' after 'customer_id'
columns_df3.insert(customer_id_index + 1, 'customer_name')

df3 = df3[columns_df3]
display(df3.head())

ValueError: list.remove(x): x not in list

In [ ]:
df3['customer_name'] = df3['first_name'] + " " + df3['last_name']

In [ ]:
df3.drop(['first_name', 'last_name'], axis=1, inplace=True)

In [ ]:
df3['phone'] = df3['phone'].fillna("Not Avalable")

In [ ]:
df3.dtypes

customer_id       int64
customer_name    object
phone            object
email            object
street           object
city             object
state            object
zip_code          int64
dtype: object

In [ ]:
df3.isnull().sum()

customer_id       0
first_name        0
last_name         0
phone          1267
email             0
street            0
city              0
state             0
zip_code          0
dtype: int64

In [ ]:
df5 = pd.read_csv('orders.csv')

In [ ]:
df5.head()

,order_id,customer_id,order_status,order_date,required_date,shipped_date,store_id,staff_id
0,1,259,4,2016-01-01,2016-01-03,2016-01-03,1,2
1,2,1212,4,2016-01-01,2016-01-04,2016-01-03,2,6
2,3,523,4,2016-01-02,2016-01-05,2016-01-03,2,7
3,4,175,4,2016-01-03,2016-01-04,2016-01-05,1,3
4,5,1324,4,2016-01-03,2016-01-06,2016-01-06,2,6

In [ ]:
df5['shipped_date'].count()

np.int64(1445)

In [ ]:
df5.isnull().sum()

order_id           0
customer_id        0
order_status       0
order_date         0
required_date      0
shipped_date     170
store_id           0
staff_id           0
dtype: int64

In [ ]:
df5['shipped_date'].dropna()

0       2016-01-03
1       2016-01-03
2       2016-01-03
3       2016-01-05
4       2016-01-06
           ...
1473    2018-04-02
1474    2018-03-31
1475    2018-04-01
1476    2018-04-01
1477    2018-04-02
Name: shipped_date, Length: 1445, dtype: object

In [ ]:
df5.head()

,order_id,customer_id,order_status,order_date,required_date,shipped_date,store_id,staff_id
0,1,259,4,2016-01-01,2016-01-03,2016-01-03,1,2
1,2,1212,4,2016-01-01,2016-01-04,2016-01-03,2,6
2,3,523,4,2016-01-02,2016-01-05,2016-01-03,2,7
3,4,175,4,2016-01-03,2016-01-04,2016-01-05,1,3
4,5,1324,4,2016-01-03,2016-01-06,2016-01-06,2,6

In [ ]:
df5.isnull().sum()

order_id           0
customer_id        0
order_status       0
order_date         0
required_date      0
shipped_date     170
store_id           0
staff_id           0
dtype: int64

In [ ]:
df6 = pd.read_csv('products.csv')

In [ ]:
df6.head()

,product_id,product_name,brand_id,category_id,model_year,list_price
0,1,Trek 820 - 2016,9,6,2016,379.99
1,2,Ritchey Timberwolf Frameset - 2016,5,6,2016,749.99
2,3,Surly Wednesday Frameset - 2016,8,6,2016,999.99
3,4,Trek Fuel EX 8 29 - 2016,9,6,2016,2899.99
4,5,Heller Shagamaw Frame - 2016,3,6,2016,1320.99

In [ ]:
df6.isnull().sum()

product_id      0
product_name    0
brand_id        0
category_id     0
model_year      0
list_price      0
dtype: int64

In [ ]:
df2 = pd.read_csv('categories.csv')

In [ ]:
df2['category_name'].unique()

array(['Children Bicycles', 'Comfort Bicycles', 'Cruisers Bicycles',
       'Cyclocross Bicycles', 'Electric Bikes', 'Mountain Bikes',
       'Road Bikes'], dtype=object)

In [ ]:
df2.head()

   category_id        category_name
0            1    Children Bicycles
1            2     Comfort Bicycles
2            3    Cruisers Bicycles
3            4  Cyclocross Bicycles
4            5       Electric Bikes

In [ ]:
df2.isnull().sum()

category_id      0
category_name    0
dtype: int64

In [ ]:
df1 = pd.read_csv('brands.csv')

In [ ]:
df1.head()

   brand_id   brand_name
0         1      Electra
1         2         Haro
2         3       Heller
3         4  Pure Cycles
4         5      Ritchey

In [ ]:
df1['brand_name'].unique()

array(['Electra', 'Haro', 'Heller', 'Pure Cycles', 'Ritchey', 'Strider',
       'Sun Bicycles', 'Surly', 'Trek'], dtype=object)

In [ ]:
df1.isnull().sum()

brand_id      0
brand_name    0
dtype: int64

In [ ]:
df4 = pd.read_csv('order_items.csv')

In [ ]:
df4.head()

   order_id  item_id  product_id  quantity  list_price  discount
0         1        1          20         1      599.99      0.20
1         1        2           8         2     1799.99      0.07
2         1        3          10         2     1549.00      0.05
3         1        4          16         2      599.99      0.05
4         1        5           4         1     2899.99      0.20

In [ ]:
df4.isnull().sum()

order_id      0
item_id       0
product_id    0
quantity      0
list_price    0
discount      0
dtype: int64

In [ ]:
df7 = pd.read_csv('staffs.csv')

In [ ]:
df7.head(10)

,staff_id,first_name,last_name,email,phone,active,store_id,manager_id
0,1,Fabiola,Jackson,fabiola.jackson@bikes.shop,(831) 555-5554,1,1,NaN
1,2,Mireya,Copeland,mireya.copeland@bikes.shop,(831) 555-5555,1,1,1.0
2,3,Genna,Serrano,genna.serrano@bikes.shop,(831) 555-5556,1,1,2.0
3,4,Virgie,Wiggins,virgie.wiggins@bikes.shop,(831) 555-5557,1,1,2.0
4,5,Jannette,David,jannette.david@bikes.shop,(516) 379-4444,1,2,1.0
5,6,Marcelene,Boyer,marcelene.boyer@bikes.shop,(516) 379-4445,1,2,5.0
6,7,Venita,Daniel,venita.daniel@bikes.shop,(516) 379-4446,1,2,5.0
7,8,Kali,Vargas,kali.vargas@bikes.shop,(972) 530-5555,1,3,1.0
8,9,Layla,Terrell,layla.terrell@bikes.shop,(972) 530-5556,1,3,7.0
9,10,Bernardine,Houston,bernardine.houston@bikes.shop,(972) 530-5557,1,3,7.0

In [ ]:
df7['staff_name'] = df7['first_name'] + " " + df7['last_name']

In [ ]:
df7.head()

,staff_id,email,phone,active,store_id,manager_id,staff_name
0,1,fabiola.jackson@bikes.shop,(831) 555-5554,1,1,NaN,Fabiola Jackson
1,2,mireya.copeland@bikes.shop,(831) 555-5555,1,1,1.0,Mireya Copeland
2,3,genna.serrano@bikes.shop,(831) 555-5556,1,1,2.0,Genna Serrano
3,4,virgie.wiggins@bikes.shop,(831) 555-5557,1,1,2.0,Virgie Wiggins
4,5,jannette.david@bikes.shop,(516) 379-4444,1,2,1.0,Jannette David

In [ ]:
columns = df7.columns.tolist()
# Remove staff_name from its current position
columns.remove('staff_name')
# Find the index of 'staff_id'
staff_id_index = columns.index('staff_id')
# Insert 'staff_name' after 'staff_id'
columns.insert(staff_id_index + 1, 'staff_name')

df7 = df7[columns]
display(df7.head())

,staff_id,staff_name,email,phone,active,store_id,manager_id
0,1,Fabiola Jackson,fabiola.jackson@bikes.shop,(831) 555-5554,1,1,NaN
1,2,Mireya Copeland,mireya.copeland@bikes.shop,(831) 555-5555,1,1,1.0
2,3,Genna Serrano,genna.serrano@bikes.shop,(831) 555-5556,1,1,2.0
3,4,Virgie Wiggins,virgie.wiggins@bikes.shop,(831) 555-5557,1,1,2.0
4,5,Jannette David,jannette.david@bikes.shop,(516) 379-4444,1,2,1.0

In [ ]:
df7.drop(['first_name', 'last_name'], axis=1, inplace=True)

In [ ]:
df7['manager_id'].count()

np.int64(9)

In [ ]:
df7.isnull().sum()

staff_id      0
first_name    0
last_name     0
email         0
phone         0
active        0
store_id      0
manager_id    1
dtype: int64

In [ ]:
df8 = pd.read_csv('stocks.csv')

In [ ]:
df8.head()

   store_id  product_id  quantity
0         1           1        27
1         1           2         5
2         1           3         6
3         1           4        23
4         1           5        22

In [ ]:
df8.isnull().sum()

store_id      0
product_id    0
quantity      0
dtype: int64